[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
  let g:winresizer_start_key = '<Leader>t'
'''

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'liuchengxu/vista.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
colorscheme iceberg

highlight Normal ctermbg=none
highlight NonText ctermbg=none
highlight LineNr ctermbg=none
highlight Folded ctermbg=none
highlight EndOfBuffer ctermbg=none
'''

## fern start
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add='''
let g:fern#default_hidden = 1
nnoremap <Leader>b :Fern . -reveal=% -drawer -toggle -width=40<CR>
'''

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
## fern end

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add ='''
let g:auto_save = 1
let g:auto_save_in_insert_mode = 0
'''

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  nnoremap <C-f> :GFiles<CR>
  nnoremap <C-l> :Files<CR>

  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''


[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = '''
source ~/.config/nvim/rc/syntastic.rc.vim
'''

[[plugins]]
repo = 'github/copilot.vim'
