[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
source ~/.config/nvim/rc/LanguageClient-neovim.vim
'''

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'liuchengxu/vista.vim'

# [[plugins]]
# repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add ='''
colorscheme iceberg
'''

## fern start
[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'

[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
## fern end

[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add ='''
let g:auto_save = 1
let g:auto_save_in_insert_mode = 0
'''

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "alvan/vim-closetag"
hook_add ='''
let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.erb,*.php,*.vue'
'''

[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'ngmy/vim-rubocop'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_add = '''
  nnoremap <C-f> :GFiles<CR>

  command! -bang -nargs=* Rg
    \ call fzf#vim#grep(
    \   'rg --line-number --no-heading '.shellescape(<q-args>), 0,
    \   fzf#vim#with_preview({'options': '--exact --reverse'}, 'right:50%:wrap'))
'''

[[plugins]]
repo = 'jparise/vim-graphql'


[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
  autocmd FileType vue syntax sync fromstart
'''

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown']
hook_add = '''
source ~/.config/nvim/rc/vim-prettier.rc.vim
'''


[[plugins]]
repo = 'leafgarland/typescript-vim'


[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add = '''
source ~/.config/nvim/rc/syntastic.rc.vim
'''

[[plugins]]
repo = 'mtscout6/syntastic-local-eslint.vim'
hook_add = '''
'''

