
[[plugins]]
repo = 'jparise/vim-graphql'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown', 'typescriptreact', 'javascriptreact']


[[plugins]]
repo = 'posva/vim-vue'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown', 'typescriptreact', 'javascriptreact']
hook_add = '''
  autocmd FileType vue syntax sync fromstart
'''

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown', 'typescriptreact', 'javascriptreact']
hook_add = '''
source ~/.config/nvim/rc/vim-prettier.rc.vim
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown', 'typescriptreact', 'javascriptreact']

[[plugins]]
repo = 'mtscout6/syntastic-local-eslint.vim'
hook_add = '''
'''
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown', 'typescriptreact', 'javascriptreact']

[[plugins]]
repo = "alvan/vim-closetag"
hook_add ='''
let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.erb,*.php,*.vue'
'''

[[plugins]]
repo = "Valloric/MatchTagAlways"
hook_add ='''
let g:mta_use_matchparen_group = 1

let g:mta_filetypes = {
    \ 'html' : 1,
    \ 'xhtml' : 1,
    \ 'xml' : 1,
    \ 'jinja' : 1,
    \ 'php' : 1,
    \ 'typescript' : 1,
    \ 'typescriptreact' : 1,
    \ 'vue' : 1,
    \}
'''
on_ft = ['javascript', 'typescript', 'vue', 'css', 'scss', 'json', 'markdown', 'typescriptreact', 'javascriptreact']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# golang START
[[plugins]]
repo = 'sebdah/vim-delve'

[[plugins]]
repo = 'mattn/vim-goimports'
# golang end


# ruby START
[[plugins]]
repo = 'ngmy/vim-rubocop'
on_ft = ['ruby']

[[plugins]]
repo = 'noprompt/vim-yardoc'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-dispatch'
on_ft = ['ruby']

[[plugins]]
repo = 'thoughtbot/vim-rspec'
on_ft = ['ruby']
hook_add ='''
let g:rspec_command = 'Dispatch bundle exec rspec --color {spec}'

map <Leader>c :call RunCurrentSpecFile()<CR>
map <Leader>l :call RunNearestSpec()<CR>
map <Leader>n :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>
'''

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = ['ruby']

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']
hook_add = '''
syntax enable
filetype plugin indent on
'''
# ruby END

# rust START
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = ['rust']
hook_add = '''
syntax enable
filetype plugin indent on
let g:rustfmt_autosave = 1
'''
# rust END
